on:
  release:
    types: [ "published", "edited" ]

jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml
  add-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ toJson(github) }}
      - uses: actions/download-artifact@v4
        with:
          name: punch-latest
