on:
  release:
    types: [ "published", "edited" ]

jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml
  add-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artifacts
      - id: download-latest-jar
        uses: actions/download-artifact@v4
        with:
          name: punch-latest
          path: ./artifacts/
      - id: get-jar-path
        run: echo "jar-path=$(ls ${{steps.download-latest-jar.outputs.download-path}}/punch-*.jar)" >> $GITHUB_OUTPUT
      - run: echo "jar path: ${{steps.get-jar-path.outputs.jar-path}}"
      - id: get-jar-name
        run: echo "jar-name=$(basename ${{steps.get-jar-path.outputs.jar-path}})" >> $GITHUB_OUTPUT
      - run: echo "jar name is ${{ steps.get-jar-name.outputs.jar-name }}"
      # - run: |
      #     gh api \
      #       --method POST \
      #       -H "Accept: application/vnd.github+json" \
      #       -H "Content-Type: application/java-archive" \
      #       -H "X-GitHub-Api-Version: 2022-11-28" \
      #       -H "User-Agent: ${{github.actor}}" \
      #       --hostname "github.com" \
      #       /repos/${{github.repository}}/releases/tag/${{github.ref_name}}/assets?name= \
      #        -f @???
          
