on:
  release:
    types: [ "published", "edited" ]

jobs:
  build:
    uses: ./.github/workflows/gradle-build.yml
  add-jar:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
      - uses: actions/checkout@v4
      - run: mkdir artifacts
      - uses: actions/download-artifact@v4
        with:
          name: punch-latest
          path: ./artifacts/
      - uses: actions/upload-artifact@v4
        with:
          path: artifacts/punch-*.jar
          name: punch-latest-published
          
